name=ByteRingBuffer
version=0.1.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Byte-based Ring buffer functionality.
paragraph=The class provides the functionality of a byte-based ring buffer with independent read and write access.
category=Other
url=https://github.com/TobiasKnauss/ArduinoLib_ByteRingBuffer
architectures=*
