name=BytesBuffer
version=0.3.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Byte-based buffer functionality, as linear or ring buffer.
paragraph=The class provides the functionality of a byte-based linear buffer or ring buffer with independent read and write access.
category=Other
url=https://github.com/TobiasKnauss/ArduinoLib_BytesBuffer
architectures=*
depends=FastCRC
